# Generated by Django 3.0.13 on 2021-03-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='static/recipes/images/content/atayeb_logo_300.png', null=True, upload_to='logo_pics', verbose_name='لوجو الموقع')),
                ('title', models.CharField(max_length=64, verbose_name='اسم الموقع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name_plural': 'هوية الموقع',
            },
        ),
    ]
