# Generated by Django 3.0.13 on 2021-03-24 00:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faqquestionbanner_faqshortbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, default='static/recipes/images/assets/default_profile_picture.png', force_format='PNG', keep_meta=True, quality=100, size=[750, 750], upload_to='about_pics', verbose_name='الصورة')),
                ('name', models.CharField(max_length=128, verbose_name='الاسم')),
                ('position', models.CharField(max_length=128, verbose_name='الوظيفة')),
                ('more_info', models.CharField(max_length=256, verbose_name='تفاصيل اخري')),
                ('facebook_url', models.URLField(blank=True, max_length=128, verbose_name='الملف الشخصي علي فيسبوك')),
                ('twitter_url', models.URLField(blank=True, max_length=128, verbose_name='الملف الشخصي علي تويتر')),
                ('instgram_url', models.URLField(blank=True, max_length=128, verbose_name='الملف الشخصي علي انستجرام')),
            ],
            options={
                'verbose_name_plural': 'كروت التعريف',
            },
        ),
        migrations.CreateModel(
            name='AboutUsParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='العنوان')),
                ('descreption', models.TextField(max_length=1024, verbose_name='التفاصيل')),
            ],
            options={
                'verbose_name_plural': 'فقرات الكتابة',
            },
        ),
    ]
