# Generated by Django 3.0.13 on 2021-03-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutuscard_aboutusparagraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationURL', models.URLField(max_length=1024, verbose_name='رابط العنوان')),
            ],
            options={
                'verbose_name_plural': 'العنوان',
            },
        ),
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='البريد الالكتروني')),
                ('address', models.CharField(max_length=128, verbose_name='العنوان')),
                ('message', models.TextField(max_length=1024, verbose_name='الرسالة')),
            ],
            options={
                'verbose_name_plural': 'رسائل الزوار',
            },
        ),
        migrations.CreateModel(
            name='ContactParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='العنوان')),
                ('descreption', models.TextField(max_length=1024, verbose_name='التفاصيل')),
            ],
            options={
                'verbose_name_plural': 'فقرات الكتابة',
            },
        ),
        migrations.CreateModel(
            name='ContactSideParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='العنوان')),
                ('descreption', models.TextField(max_length=1024, verbose_name='التفاصيل')),
            ],
            options={
                'verbose_name_plural': 'فقرات الكتابة الجانبية',
            },
        ),
    ]
