# Generated by Django 3.0.13 on 2021-03-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactlocation_contactmessages_contactparagraph_contactsideparagraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuscard',
            options={'verbose_name_plural': 'كروت التعريف - معلومات عنا'},
        ),
        migrations.AlterModelOptions(
            name='aboutusparagraph',
            options={'verbose_name_plural': 'فقرات الكتابة - معلومات عنا'},
        ),
        migrations.AlterModelOptions(
            name='contactlocation',
            options={'verbose_name_plural': 'العنوان - اتصل بنا'},
        ),
        migrations.AlterModelOptions(
            name='contactmessages',
            options={'verbose_name_plural': 'رسائل الزوار - اتصل بنا'},
        ),
        migrations.AlterModelOptions(
            name='contactparagraph',
            options={'verbose_name_plural': 'فقرات الكتابة - اتصل بنا'},
        ),
        migrations.AlterModelOptions(
            name='contactsideparagraph',
            options={'verbose_name_plural': 'فقرات الكتابة الجانبية - اتصل بنا'},
        ),
    ]
