# Generated by Django 3.0.13 on 2021-03-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210324_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlocation',
            name='locationURL',
            field=models.TextField(max_length=1024, verbose_name='رابط العنوان'),
        ),
    ]
