# Generated by Django 3.0.13 on 2021-03-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210324_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
            ],
            options={
                'verbose_name_plural': 'المشتركين باخر التحديثات',
            },
        ),
    ]
