# Generated by Django 3.0.13 on 2021-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210324_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/recipes/images/content/atayeb_logo_300.png', null=True, upload_to='carousel_pics', verbose_name='الصورة')),
            ],
            options={
                'verbose_name_plural': 'logo',
            },
        ),
    ]
