# Generated by Django 3.0.13 on 2021-03-29 02:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homepagelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscard',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='static/recipes/images/assets/default_profile_picture.png', force_format='PNG', keep_meta=True, quality=100, size=[750, 750], upload_to='core_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='homepagelogo',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/recipes/images/content/atayeb_logo_300.png', force_format='PNG', keep_meta=True, null=True, quality=100, size=[50, 50], upload_to='core_images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/content/atayeb_logo_300.png', null=True, upload_to='core_images', verbose_name='الصورة'),
        ),
    ]
