# Generated by Django 3.0.13 on 2021-03-29 02:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210329_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscard',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[750, 750], upload_to='core/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='homepagelogo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format='PNG', keep_meta=True, quality=100, size=[50, 50], upload_to='logo/', verbose_name='صورة الموقع الرئيسية'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format='PNG', keep_meta=True, quality=100, size=[700, 350], upload_to='core/', verbose_name='صور الصفحة الرئيسية'),
        ),
    ]
