# Generated by Django 3.0.13 on 2021-03-29 03:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210329_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuscard',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[150, 150], upload_to='core/', verbose_name='الصورة'),
        ),
    ]
