# Generated by Django 3.0.13 on 2021-03-28 22:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/assets/default_no_pic.png', force_format='PNG', keep_meta=True, null=True, quality=100, size=[750, 750], upload_to='post_images/', verbose_name='الصورة'),
        ),
    ]
