# Generated by Django 3.0.13 on 2021-03-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210328_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'المنشورات'},
        ),
    ]
