# Generated by Django 3.0.13 on 2021-03-29 15:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210329_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format='PNG', keep_meta=True, quality=100, size=[750, 750], upload_to='post_images/', verbose_name='الصورة'),
        ),
    ]
