# Generated by Django 3.0.7 on 2020-06-05 21:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='فئة المكون')),
                ('image', models.ImageField(blank=True, default='default_ingredients.jpg', null=True, upload_to='ingredients_pics', verbose_name='الصورة')),
            ],
            options={
                'verbose_name_plural': 'فئات المكونات',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='فئة الوصفة')),
                ('image', models.ImageField(blank=True, default='default_recipe_photo.png', null=True, upload_to='recipes_pics', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name_plural': 'فئات الوصفات',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الوصفة')),
                ('recipe_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='مصدر الوصفة')),
                ('feeds_up_to', models.SmallIntegerField(default=1, verbose_name='تكفي لإطعام')),
                ('prep_time', models.CharField(max_length=50, verbose_name='وقت التحضير')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
                ('image', models.ImageField(blank=True, default='default_recipe_photo.png', null=True, upload_to='recipes_pics', verbose_name='الصورة')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeCategory', verbose_name='فئة الوصفة')),
            ],
            options={
                'verbose_name_plural': 'الوصفات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='الترتيب')),
                ('description', models.TextField(verbose_name='الشرح')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='الوصفة')),
            ],
            options={
                'verbose_name_plural': 'الخطوات',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='المكون')),
                ('image', models.ImageField(blank=True, default='default_ingredients.jpg', null=True, upload_to='ingredients_pics', verbose_name='الصورة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.IngredientCategory', verbose_name='فئة المكون')),
            ],
            options={
                'verbose_name_plural': 'المكونات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نص التعليق')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التعليق')),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.Recipe', verbose_name='التعليقات')),
            ],
            options={
                'verbose_name_plural': 'التعليقات',
                'ordering': ('-comment_date',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255, verbose_name='المقادير')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient', verbose_name='المكون')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='الوصفة')),
            ],
            options={
                'verbose_name_plural': 'مكونات الوصفة',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
