# Generated by Django 3.0.7 on 2020-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_ingredients.jpg', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_ingredients.jpg', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_recipe_photo.png', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_recipe_photo.png', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
    ]
