# Generated by Django 3.0.13 on 2021-03-17 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20200611_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='RecipeComment',
        ),
        migrations.RenameModel(
            old_name='Instruction',
            new_name='RecipeInstruction',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_no_pic.png.jpg', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_no_pic.png.jpg', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_no_pic.png', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, default='static/recipes/images/assets/default_no_pic.png.png', null=True, upload_to='recipes_pics', verbose_name='الصورة'),
        ),
    ]
