# Generated by Django 3.0.13 on 2021-03-17 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210317_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeinstruction',
            options={'ordering': ('order',), 'verbose_name_plural': 'الخطوات'},
        ),
        migrations.RenameField(
            model_name='recipeinstruction',
            old_name='number',
            new_name='order',
        ),
    ]
