# Generated by Django 3.0.13 on 2021-03-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210317_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNutritionFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('اجمالي الدهون', 'اجمالي الدهون'), ('حجم الوجبة', 'حجم الوجبة'), ('سعرات حراريه', 'سعرات حراريه'), ('الدهون المشبعة', 'الدهون المشبعة'), ('دهون غير مشبعة', 'دهون غير مشبعة'), ('الدهون الأحادية غير المشبعة', 'الدهون الأحادية غير المشبعة'), ('صوديوم', 'صوديوم'), ('ألياف', 'ألياف'), ('الكوليسترول', 'الكوليسترول'), ('الدهون المتحولة', 'الدهون المتحولة'), ('اجمالي الكربوهيدرات', 'اجمالي الكربوهيدرات'), ('البروتين', 'البروتين'), ('سكر', 'سكر')], max_length=128, verbose_name='العنصر')),
                ('quantity', models.CharField(max_length=255, verbose_name='الكمية')),
                ('daily_percent', models.PositiveSmallIntegerField(verbose_name='المقادير اليومية')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='الوصفة')),
            ],
            options={
                'verbose_name_plural': 'الحقائق الغذائية للوصفة',
                'unique_together': {('recipe', 'element')},
            },
        ),
    ]
