# Generated by Django 3.0.13 on 2021-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipenutritionfacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipenutritionfacts',
            name='daily_percent',
            field=models.PositiveSmallIntegerField(verbose_name='نسبة المقادير اليومية'),
        ),
    ]
