# Generated by Django 3.0.13 on 2021-03-22 00:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210322_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/recipes/images/assets/default_no_pic.png', force_format='PNG', keep_meta=True, null=True, quality=75, size=[300, 300], upload_to='recipes_pics', verbose_name='الصورة'),
        ),
    ]
