# Generated by Django 3.0.13 on 2021-03-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210322_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_source',
        ),
        migrations.AlterField(
            model_name='recipenutritionfacts',
            name='element',
            field=models.CharField(choices=[('اجمالي الدهون', 'اجمالي الدهون'), ('حجم الوجبة', 'حجم الوجبة'), ('سعرات حراريه', 'سعرات حراريه'), ('الدهون المشبعة', 'الدهون المشبعة'), ('دهون غير مشبعة', 'دهون غير مشبعة'), ('الدهون الأحادية غير المشبعة', 'الدهون الأحادية غير المشبعة'), ('صوديوم', 'صوديوم'), ('ألياف', 'ألياف'), ('الكوليسترول', 'الكوليسترول'), ('الدهون المتحولة', 'الدهون المتحولة'), ('اجمالي الكربوهيدرات', 'اجمالي الكربوهيدرات'), ('البروتين', 'البروتين'), ('سكر', 'سكر'), ('البوتاسبوم', 'البوتاسيوم')], max_length=128, verbose_name='العنصر'),
        ),
    ]
