# Generated by Django 3.0.13 on 2021-03-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210323_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomment',
            name='active',
        ),
    ]
