# Generated by Django 3.0.13 on 2021-03-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_bookmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'verbose_name_plural': 'الوصفات المفضلة'},
        ),
    ]
