# Generated by Django 3.0.13 on 2021-03-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20210324_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='user',
            new_name='profile',
        ),
    ]
