# Generated by Django 3.0.7 on 2020-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/recipes/images/assets/default_profile_picture.png', upload_to='profile_pics'),
        ),
    ]
