# Generated by Django 3.0.13 on 2021-03-23 20:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200611_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='static/recipes/images/assets/default_profile_picture.png', force_format='PNG', keep_meta=True, quality=75, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
