# Generated by Django 3.0.13 on 2021-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210323_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Contributer User', max_length=250),
        ),
    ]
